### ISSUE TITLE
Not rendering

### ISSUE THREAD

**Issue by MrSonicMaster** [zadvorsky/three.portals#2]
I understand this project is pretty old, but it's awesome and the best one (out of 2) out there. I simply cannnot get the portals to render in my world, following everything there is to be seen in the example and fixing up some outdated parts from the code (mainly MeshFaceMaterial being removed.)

No matter WHAT I try (making the portals super large, changing position, changing rotation, etc.) nothing renders. I'm not expecting a reply (or a fast reply) but maybe somebody would come across this and be able to help.

**Comment by zadvorsky** [comment]
Can you share the code?

What do you see in the portals? Are they back? White?

Can you revert back to an earlier version of three and check if it works there?

**Comment by MrSonicMaster** [comment]
Absolutely nothong at all renders, as if I never created them. I followed the same exact code in the example. Honestly, I even downloaded the example and nothing rendered when using the latest threejs, so I downloaded the threejs used on the example website and that allowed my local copy of the example to render and function properly. The same could not be said for my actual game code, switching to the old threejs yields no portal rendering whatsoever. I can put logs everywhere and they all get called: the portals are created, the scene is registered, the scene is set, and the portal render functions even get called. I can log the coordinates and those all check out, everything looks perfectly fine; just nothing shows up! I'm not home right now but i can share code samples when I'm back, just know its essentially the same principal of whats in example.js and nothing new or fancy added yet (that comes after it actually works)

**Comment by MrSonicMaster** [comment]
Absolutely nothing rensers at all. It's as if they weren't created. I downloaded the github repo and tested the examples with the latest threejs and nothing rendered there either, so i downloaded the threejs used on your website example and was able to get the example to work. The same cannot be said for my actual game, downgrading to the older threejs does not allow them to render. I can put logs everywere and everything checks out: scene is registered, portals are created, position and size and everything checks out, scene is selected and the portal render functions are all called; just nothing renders in the world! The portal code is basically the same as example.js; create portal manager, register scene, add portals, select scene and pair up portals. No errors or warnings or anything in console whatsoever, just nothing shows up!

**Comment by MrSonicMaster** [comment]
To more directly answer your questions:

I'll send the important parts of my code when I get home and hopefully you will be able to help me out and/or point out mistakes.

Nothing renders at all

Older threejs works in the example, but not in my game code.

**Comment by MrSonicMaster** [comment]
```js
// Init
                this.renderer = new THREE.WebGLRenderer({
			antialias: true
			//stencil: true
		});

		this.renderer.setPixelRatio(window.devicePixelRatio);
		this.renderer.setSize(window.innerWidth, window.innerHeight);

		document.body.appendChild(this.renderer.domElement);

		this.camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 1, 1000);
		this.createScene();

// createScene
                this.scene = new THREE.Scene();
		this.scene.background = new THREE.Color(0xffffff);
		this.scene.fog = new THREE.Fog(0xffffff, 0, 750);

		const light = new THREE.HemisphereLight(0xeeeeff, 0x777788, 0.75);
		light.position.set(0.5, 1, 0.75);
		this.scene.add(light);

// create walls (called in init)

                const loader = new THREE.TextureLoader();

		loader.load('./assets/image/wallTexture.jpg', map => {
			map.wrapS = map.wrapT = THREE.RepeatWrapping;
			map.offset.set(0, 0);

			map.repeat.set(2, 2);

			const wallSize = 50;
			const wallPos = 50;

			const geometry = new THREE.BoxGeometry(wallSize, wallSize, 5);
			const material = new THREE.MeshBasicMaterial({ map });

			const frontWall = new THREE.Mesh(geometry, material);
			frontWall.position.set(0, 20, -wallPos);
			this.add(frontWall);

			const backWall = new THREE.Mesh(geometry, material);
			backWall.position.set(0, 20, wallPos);
			backWall.rotation.set(0, Math.PI, 0);
			this.add(backWall);

			this.addPortals(frontWall, backWall);
		});

		loader.load('./assets/image/wallTexture.jpg', map => {
			map.wrapS = map.wrapT = THREE.RepeatWrapping;
			map.offset.set(0, 0);

			map.repeat.set(40, 40);

			const floorGeometry = new THREE.PlaneGeometry(1000, 1000, 100, 100);
			const floorMaterial = new THREE.MeshBasicMaterial({ map });
			floorGeometry.rotateX(-Math.PI / 2);

			const floor = new THREE.Mesh(floorGeometry, floorMaterial);

			this.scene.add(floor);
		});

// And finally portals

                this.portalController = new THREE.PortalController({
			renderer: this.renderer,
			camera: this.camera
		});

		// this.controls = this.portalController.cameraControls;

		this.portalController.registerScene('scene1', this.scene);

		const portal1 = this.portalController.createPortal(20, 20, 'scene1');
		portal1.position.copy(frontWall.position);

		const portal2 = this.portalController.createPortal(20, 20, 'scene1');
		portal2.position.copy(backWall.position);
		portal2.rotateY(Math.PI);

		portal1.setDestinationPortal(portal2);
		portal2.setDestinationPortal(portal1);

		this.portalController.setCurrentScene('scene1');
```

using the same portal code (with position.copy) & wall code, I can get this to work in the example but it won't work in my actual game client.

**Comment by MrSonicMaster** [comment]
I decided to just code my own portals basing it off yours and another portal library that I found. Now I've got recursive rendering portals (seeing portals through portals) that render perfectly (except teleportation... guess they aren't portals yet. I'll get to that soon.) Thank's for the help anyways though.
